version: "3"
services:
  telegram-webhook:
    image: 172232502/telegram-webhook:latest
    restart: always
    volumes:
      - ./.env:/app/.env
    #   - ./json:/usr/share/nginx/html/json
    ports:
      - 3010:3010
